name: dotnet-runtime-deps-ubuntu

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  UBUNTU_JAMMY: ubuntu-22.04

jobs:
  ubuntu-jammy-amd64:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - id: qemu
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - id: setup_buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: meta
        name: Extract metadata (tags, labels) for Docker
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,enable=true,priority=100,prefix=${{ env.UBUNTU_JAMMY }}-,suffix=-amd64,format=short
            type=ref,enable=true,priority=600,prefix=${{ env.UBUNTU_JAMMY }}-,suffix=-amd64,event=tag
            type=raw,enable=true,priority=200,prefix=${{ env.UBUNTU_JAMMY }}-,suffix=-amd64,value=latest
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:ubuntu/22.04"
          file: Dockerfile.amd64
          push: true
          build-contexts: |
            ubuntu=docker-image://ubuntu:22.04
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
  ubuntu-jammy-cross-s390x:
    runs-on: ubuntu-latest
    needs: ubuntu-jammy-amd64
    permissions:
      contents: read
      packages: write
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - id: qemu
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - id: setup_buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: meta
        name: Extract metadata (tags, labels) for Docker
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,enable=true,priority=100,prefix=${{ env.UBUNTU_JAMMY }}-,suffix=-cross-s390x,format=short
            type=ref,enable=true,priority=600,prefix=${{ env.UBUNTU_JAMMY }}-,suffix=-cross-s390x,event=tag
            type=raw,enable=true,priority=200,prefix=${{ env.UBUNTU_JAMMY }}-,suffix=-cross-s390x,value=latest
      - name: lowercase
        run: |
          echo "IMAGE_NAME=${IMAGE_NAME,,}" >> ${GITHUB_ENV}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:ubuntu/22.04"
          file: Dockerfile.cross.s390x
          push: true
          build-contexts: |
            ubuntu=docker-image://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.UBUNTU_JAMMY }}-latest-amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
