name: Ubuntu 22.04 (Jammy)

on:
  workflow_dispatch:
  
  push:
    branches:    
      - main
      - 'releases/**'
    tags:        
      - v*
    paths:
      - 'ubuntu/**'
      - '!**/*.md'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  UBUNTU_VERSION: 22.04

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
      - id: qemu
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - id: setup_buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: meta
        name: Extract metadata (tags, labels) for Docker
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,enable=true,priority=600,prefix=ubuntu-${{ env.UBUNTU_VERSION }}-,suffix=-amd64,event=tag
            type=raw,enable=true,priority=201,prefix=ubuntu-${{ env.UBUNTU_VERSION }}-,suffix=,value=latest
            type=raw,enable=true,priority=200,prefix=ubuntu-${{ env.UBUNTU_VERSION }}-,suffix=-amd64,value=latest
            type=sha,enable=true,priority=100,prefix=ubuntu-${{ env.UBUNTU_VERSION }}-,suffix=-amd64,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:ubuntu/${{ env.UBUNTU_VERSION }}"
          allow: |
            security.insecure
          file: Dockerfile
          push: true
          build-contexts: |
            ubuntu=docker-image://ubuntu:${{ env.UBUNTU_VERSION }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
